[package]
name = "box_planner_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv   = "1.1"
thiserror = "1.0"
confy = "0.6"

[dev-dependencies]
tempfile = "3"
